// <auto-generated />
using DotNetExam;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetExam.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240109110515_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLibrary.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ac")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ac = 15,
                            AttackModifier = 5,
                            AttackPerRound = 1,
                            Damage = "1d6",
                            DamageModifier = 6,
                            HitPoints = 40,
                            Name = "Lizardfolk"
                        },
                        new
                        {
                            Id = 2,
                            Ac = 10,
                            AttackModifier = 6,
                            AttackPerRound = 2,
                            Damage = "1d4",
                            DamageModifier = 7,
                            HitPoints = 40,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 3,
                            Ac = 13,
                            AttackModifier = 6,
                            AttackPerRound = 1,
                            Damage = "1d6",
                            DamageModifier = 8,
                            HitPoints = 40,
                            Name = "Skeleton"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
